import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const manrope = localFont({
  src: '../font/Manrope/Manrope-VariableFont_wght.ttf',
  variable: '--font-manrope',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} font-sans`}>{children}</body>
    </html>
  );
}
