import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const montserrat = localFont({
  src: '../font/Montserrat/Montserrat-VariableFont_wght.ttf',
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${montserrat.className}`}>{children}</body>
    </html>
  );
}
